//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KT_5.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public int id { get; set; }
        public int RoleId { get; set; }
        public string lastname { get; set; }
        public string name { get; set; }
        public string patronymic { get; set; }
        public string email { get; set; }
        public string login { get; set; }
        public string password { get; set; }
        public string phone { get; set; }
        public int passportSeries { get; set; }
        public int passportNumber { get; set; }
        public System.DateTime BirthDate { get; set; }
        public Nullable<System.DateTime> LastAuthDateTime { get; set; }
        public Nullable<int> AuthTypeId { get; set; }
        public int GenderId { get; set; }
    
        public virtual AuthTypes AuthTypes { get; set; }
        public virtual Genders Genders { get; set; }
        public virtual Roles Roles { get; set; }
    }
}
